import {decodeLocation,appLink,STORE} from './codec.mjs';
import {PairedSample} from './audio.mjs';
const $=id=>document.getElementById(id);
const copy={ko:{title:'세 부품, 하나의 타건감',sound:'먼저, 소리로 만나보세요',visual:'먼저, 소재를 살펴보세요',intro:'공유받은 조합의 실제 부품과 스위치 소리를 로그인 없이 체험하세요.',listen:'들어보기',stop:'재생 취소',mute:'음소거',copy:'조합 코드 복사',open:'앱에서 열기',store:'Google Play',code:'공유받은 조합 코드',privacy:'쿠키·분석·사용자 식별자를 사용하지 않습니다. 체험은 소유권이나 보상을 제공하지 않습니다. 앱에서 보유한 세 부품을 확인한 뒤 직접 적용하세요. 앱이 열리지 않으면 코드를 복사해 앱에서 가져오세요.',invalid:'유효한 조합 링크가 아닙니다. 보낸 사람에게 코드를 다시 요청하세요.',unavailable:'이 부품의 웹 아트는 아직 준비되지 않았습니다. 코드는 앱에서 사용할 수 있습니다.',playing:'두 번의 타건을 재생 중입니다.',copied:'코드를 복사했습니다.',failed:'작업을 완료하지 못했습니다. 코드를 직접 선택해 복사할 수 있습니다.',kinds:['키캡','스위치','스프링']},en:{title:'Three parts. One feel.',sound:'Start with the sound',visual:'Look closer at the materials',intro:'Explore the shared parts and their real switch sound. No login needed.',listen:'Listen',stop:'Cancel audio',mute:'Mute',copy:'Copy combination code',open:'Open in app',store:'Google Play',code:'Shared combination code',privacy:'No cookies, analytics or user identifiers. This preview grants no ownership or rewards. In the app, check all three owned parts and apply explicitly. If the app does not open, copy and import the code.',invalid:'Invalid combination link. Ask the sender for the code again.',unavailable:'Web artwork is unavailable for this part. Keep the code to preview in the app.',playing:'Playing two paired strokes.',copied:'Code copied.',failed:'Unable to finish. You can select and copy the code manually.',kinds:['Keycap','Switch','Spring']},ja:{title:'三つのパーツ、一つの打鍵感',sound:'まず、音を聴いてみましょう',visual:'まず、素材を見てみましょう',intro:'共有されたパーツと実際のスイッチ音を、ログインなしで体験できます。',listen:'聴いてみる',stop:'再生を中止',mute:'ミュート',copy:'組み合わせコードをコピー',open:'アプリで開く',store:'Google Play',code:'共有された組み合わせコード',privacy:'Cookie・分析・ユーザー識別子は使用しません。所有権や報酬は付与されません。アプリで三つのパーツの所有を確認し、自分で適用してください。開かない場合はコードをコピーして取り込めます。',invalid:'無効なリンクです。送信者にコードを確認してください。',unavailable:'このパーツのWebアートは未対応です。コードはアプリで使えます。',playing:'二回の打鍵を再生しています。',copied:'コピーしました。',failed:'完了できませんでした。コードを選択してコピーできます。',kinds:['キーキャップ','スイッチ','スプリング']}};
let catalog, combination, player, lang=['ko','en','ja'].includes(navigator.language.slice(0,2))?navigator.language.slice(0,2):'en';
const t=()=>copy[lang];
function render(){document.documentElement.lang=lang;document.title='Key Ddal · '+t().title;$('languageLabel').textContent={ko:'언어',en:'Language',ja:'言語'}[lang];$('locale').value=lang;$('title').textContent=t().title;$('intro').textContent=t().intro;$('eyebrow').textContent=combination?.variant==='sound'?t().sound:combination?.variant==='visual'?t().visual:'Key Ddal';for(const id of ['listen','stop','copy','open','store'])$(id).textContent=t()[id];$('codeLabel').textContent=t().code;$('muteLabel').textContent=t().mute;$('privacy').textContent=t().privacy;$('store').href=STORE;$('parts').replaceChildren();if(!combination)return;combination.ids.forEach((id,i)=>{const part=catalog.parts[id],figure=document.createElement('figure');if(part.art && /^assets\/[a-zA-Z0-9_./-]+\.webp$/.test(part.art)&&!part.art.includes('..')){const img=document.createElement('img');img.src=part.art;img.width=192;img.height=192;img.alt=part.names[lang];figure.append(img);}else{const missing=document.createElement('p');missing.textContent=t().unavailable;figure.append(missing);}const caption=document.createElement('figcaption');caption.textContent=`${t().kinds[i]} · ${part.names[lang]}`;figure.append(caption);$('parts').append(figure);});$('code').value=combination.code;$('copy').disabled=false;$('open').hidden=false;$('open').href=appLink(combination.code,catalog.parts);$('listen').disabled=$('mute').checked;}
$('locale').onchange=()=>{player?.stop();lang=$('locale').value;render();if(!combination)$('status').textContent=t().invalid;};
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(combination.code);$('status').textContent=t().copied;}catch{$('code').select();$('status').textContent=t().failed;}};
$('listen').onclick=async()=>{if($('mute').checked||document.hidden)return;try{await player.play(catalog.parts[combination.ids[1]].audio);}catch{$('status').textContent=t().failed;}};
$('stop').onclick=()=>player?.stop();$('mute').onchange=()=>{player?.stop();render();};
document.addEventListener('visibilitychange',()=>{if(document.hidden)player?.stop();});addEventListener('pagehide',()=>player?.stop());addEventListener('hashchange',()=>{player?.stop();location.reload();});
render();
try{const r=await fetch('catalog.json',{credentials:'omit',referrerPolicy:'no-referrer'});if(!r.ok)throw Error();catalog=await r.json();combination=decodeLocation(location.search,location.hash,catalog.parts);player=new PairedSample(catalog.gain,playing=>{$('stop').disabled=!playing;$('listen').disabled=playing||$('mute').checked;$('status').textContent=playing?t().playing:'';});render();}catch{$('status').textContent=t().invalid;}
